#### 방정식 표현하기 기초
\begin{align}
\dot{x} & = \sigma(y - x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}

#### 방정식 표현 고급 1단계
\begin{equation*}
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
\end{equation*}

In [4]:
>>> Data = {'X': [1, 2, 3], 'Y': [1, 4, 9]}
print(type(Data))
>>> for a, b in Data.items():
        #x=a[1]
        print("{x}*{x} = {y}\n".format(x=a,y=b))

<class 'dict'>
X*X = [1, 2, 3]

Y*Y = [1, 4, 9]



In [13]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import os

print(os)

<module 'os' from 'C:\\Users\\gaeasoft\\Anaconda3\\lib\\os.py'>


In [14]:
print(tf.__version__)
print(dir("tensorflow"))

1.14.0
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [1]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')

2

In [2]:
fruits.index('banana')

3

In [3]:
fruits.index('apple')

1

In [4]:
fruits.index('banana',4) #find next banana starting a position 4

6

In [5]:
fruits.append('grape')

In [6]:
fruits

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana', 'grape']

In [7]:
fruits.sort()

In [8]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [10]:
fruits.pop() #Pop the last item from the list

'pear'

In [11]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange']

In [12]:
#List Comprehensions
squares = []
for x in range(10) :
    squares.append(x**2)

In [13]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
squares = list(map(lambda x: x**2, range(10)))

In [15]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [16]:
squares = [x**2 for x in range(10)]

In [17]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [18]:
import numpy as np
#ndarray : N차원의 배열 객체
#기존 파이썬과 다르게 '같은 종류의 데이터'만 배열에 담을수 있다 한다.

#An array object represents a multidimensional, homogeneous array of fixed-size items.

In [20]:
data = [1,2,3,4,5]
arr = np.array(data)
arr

In [21]:
data = [[1,2,3,4], [5,6,7,8]]
arr = np.array(data)
arr 
#pprint 안해도 되는거 아냐?

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.09478267e-321],
       [8.45603440e-307, 1.24611470e-306, 3.44886448e-307]])

In [23]:
np.empty? 
# new array of given shape and type, without initializing entries.

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones((5,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
data = [[1,2,3,4], [5,6,7,8]]
arr = np.array(data)
arr.ndim

2

In [44]:
arr.shape

(2, 4)

In [ ]:
# data1 = [[1,2,3,4],[5,6,7,8]]
# data2 = [[11,12,13,14],[15,16,17,18]]
# arr1 = np.array(data1)
# arr2 = np.array(data2)
# np.reshape(data,data2)

In [45]:
a = np.zeros((10,2))

In [46]:
b = a.T

In [50]:
c = b.view() #New view of array with the same data.

In [51]:
c.shape = (20) #An Error occured

AttributeError: incompatible shape for a non-contiguous array

In [55]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [56]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
np.reshape(np.ravel(a), (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
arr.shape

(2, 4)

In [60]:
arr.dtype

dtype('int32')

In [61]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [62]:
float_arr = arr.astype(np.float64)
#astype을 호출하면 dtype이 같아도 항상 새로운 배열을 생성한다?
#무슨말이지?
float_arr.dtype

dtype('float64')

In [69]:
arr = np.array(['1','2','3','4','5'])
print(type(arr[0])) #둘 차이가 뭘까?
print(arr[0].dtype)

<class 'numpy.str_'>
<U1


In [70]:
int_arr = arr.astype(np.int64)
int_arr.dtype

dtype('int64')

In [71]:
int_arr

array([1, 2, 3, 4, 5], dtype=int64)

In [1]:
a = [1,2,3,4,5]

print(a[1:])

[2, 3, 4, 5]


In [13]:
b = [[1,2], [3,4]]

print(b[0][0])

1


In [ ]:
sys.path.append(os.pardir) # 부모 디렉터리의 파일을 가져올 수 있도록 설정한다