In [1]:
text = 'You say goodbye and I say hello.'

text = text.lower()           #양식통일
text = text.replace('.',' .') #나중에 split을 해주기 위해서 처리
text

'you say goodbye and i say hello .'

In [2]:
words = text.split(' ')      #단어 짜르기
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

In [3]:
word_to_id = {}
id_to_word = {}

for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word

In [4]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [5]:
word_to_id

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}

In [6]:
import numpy as np

corpus = [word_to_id[w] for w in words]
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [11]:
def preprocess(text):
    text = text.lower()
    text = text.replace('.', ' .')
    words = text.split(' ')
    word_to_id = {}
    id_to_word = {}
    for word in words:
        if word not in word_to_id:
            new_id = len(word_to_id)
            word_to_id[word] = new_id
            id_to_word[new_id] = word

    corpus = np.array([word_to_id[w] for w in words])
    
    return corpus, word_to_id, id_to_word

In [12]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

In [1]:
#벡터간 유사도
import sys
sys.path.append('..')
from common.util import preprocess, create_co_matrix, cos_similarity


text = 'You say goodbye I say Hello.'
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)

c0 = C[word_to_id['you']] #you의 단어 벡터
c1 = C[word_to_id['i']] #i의 단어 벡터
print(cos_similarity(c0, c1))
#cos 유사도는 -1~ 1 사이인데 0.7이면 상당히 큰 수치임을 알 수 있다.

0.7071067691154799


In [3]:
from common.util import preprocess, create_co_matrix, most_similar


most_similar('you', word_to_id, id_to_word, C, top = 5)

#결과가 뭔가 이상하다, corpus가 너무 작은 탓


[query] you
 goodbye: 0.7071067691154799
 i: 0.7071067691154799
 hello: 0.7071067691154799
 say: 0.0
 .: 0.0


## 2.4 통계 기반 기법 개선하기

In [5]:
from common.util import preprocess, create_co_matrix, cos_similarity, ppmi
import numpy as np

corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)
W = ppmi(C)

np.set_printoptions(precision = 3) #유효자리수를 3자리로 표시
print("동시발생 행렬")
print(C)
print('-'*50)
print('PPMI')
print(W)

동시발생 행렬
[[0 1 0 0 0 0]
 [1 0 1 1 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 0]
 [0 1 0 0 0 1]
 [0 0 0 0 1 0]]
--------------------------------------------------
PPMI
[[0.    1.585 0.    0.    0.    0.   ]
 [1.585 0.    0.585 0.585 0.585 0.   ]
 [0.    0.585 0.    1.585 0.    0.   ]
 [0.    0.585 1.585 0.    0.    0.   ]
 [0.    0.585 0.    0.    0.    2.585]
 [0.    0.    0.    0.    2.585 0.   ]]
