In [2]:
import numpy as np
import pprint
pp = pprint.PrettyPrinter(width=41, compact=True)

In [3]:
#A의 열벡터에 대한 단위벡터로 구성된 직교기저를 구하는 그람 슈미트 과정
def gram_schmidt(A):
    basis = []
    for v in A.T:
        w = v - sum(np.dot(v, b) * b for b in basis)
        if (np.abs(w) > 1e-10).any():
            basis.append(w/np.linalg.norm(w))
    return np.array(basis).T

In [7]:
A = np.array([[3, 1], [2, 2]])
pp.pprint(A)

array([[3, 1],
       [2, 2]])


In [8]:
pp.pprint(gram_schmidt(A))

array([[ 0.83205029, -0.5547002 ],
       [ 0.5547002 ,  0.83205029]])


In [9]:
B = np.array([[1,1,0], [1,3,1], [2,-1,1]])
pp.pprint(B)
pp.pprint(gram_schmidt(B))

array([[ 1,  1,  0],
       [ 1,  3,  1],
       [ 2, -1,  1]])
array([[ 0.40824829,  0.20739034, -0.88900089],
       [ 0.40824829,  0.82956136,  0.38100038],
       [ 0.81649658, -0.51847585,  0.25400025]])


In [10]:
#QR분해
C = np.array([[1, 1, 1], [2, 2, 0], [3, 0, 0], [0, 0, 1]])
Q, R = np.linalg.qr(C)

In [11]:
pp.pprint(C)
pp.pprint(Q)
pp.pprint(R)
pp.pprint(np.matmul(Q,R))

array([[1, 1, 1],
       [2, 2, 0],
       [3, 0, 0],
       [0, 0, 1]])
array([[-2.67261242e-01, -3.58568583e-01,  5.96284794e-01],
       [-5.34522484e-01, -7.17137166e-01, -2.98142397e-01],
       [-8.01783726e-01,  5.97614305e-01, -1.79001965e-16],
       [-0.00000000e+00, -0.00000000e+00,  7.45355992e-01]])
array([[-3.74165739, -1.33630621, -0.26726124],
       [ 0.        , -1.79284291, -0.35856858],
       [ 0.        ,  0.        ,  1.34164079]])
array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  2.00000000e+00, -1.08098175e-16],
       [ 3.00000000e+00, -4.44089210e-16, -7.36228837e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])


무어 펜로스 의사 역행렬 

In [12]:
A = np.array([[1,1], [2, 1], [3, 1], [4, 1]])
b = np.array([[3,5], [4, 3], [7, 2], [8, 0]])
x = np.matmul(np.matmul(np.linalg.inv(np.matmul(A.T, A)), A.T), b)

In [14]:
pp.pprint(A)
pp.pprint(b)
pp.pprint(x)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])
array([[3, 5],
       [4, 3],
       [7, 2],
       [8, 0]])
array([[ 1.8, -1.6],
       [ 1. ,  6.5]])


QR 분해를 이용한 행렬방정식의 최적근사해

In [16]:
C = np.array([[1,3,5], [1,1,0], [1,1,2], [1,3,3]])
d = np.array([[3],[5],[7],[-3]])
Q, R = np.linalg.qr(C)
x = np.matmul(np.matmul(np.linalg.inv(R), Q.T), d)

In [ ]:
pp.pprint(C)
