# 선형대수 2장 프로그래밍 실습

In [1]:
import numpy as np

O = np.zeros((2,3))

one = np.ones((2,2))

a = np.full((3,2),3)

I = np.eye(2)

print(O)
print(one)
print(a)
print(I)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[1. 0.]
 [0. 1.]]


In [2]:
#가우스 조단 소거법

In [3]:
import numpy as np
import pprint as pprint

def gauss(a):
    (n,m) = a.shape
    
    for i in n:#첫 행이 나머지 행을 서치
        if i
        
    
    """
    가우스 조단 소거법 하는법
    1.첫 행의 첫 item이 다른 행 첫 item을 칼삭하는지 확인
    된다면 ->
    
    
    2.안된다면 -> 두번째 행의 첫 item이 칼삭하는지 확인
    3.
    4.
    5.
    
    """

    
    for i in range()
    
    
    pass


#첨가행렬
a = np.array([[2,2,4,18],
             [1,3,2,13],
             [3,1,3,14]])

#3x4 형식이다.
gauss(a)

pprint.pprint(a)



array([[1., 1.],
       [1., 1.]])
