In [2]:
import torch

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
print(x.size())
print(x.shape)
print(x.ndimension())

torch.Size([3, 3])
torch.Size([3, 3])
2


In [ ]:
x = torch.unsqueeze(x, 0)
print(x)
print(x.size())
print(x.shape)
print(x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
3


랭크 늘리기

In [ ]:
x = torch.squeeze(x)
print(x)
print(x.size())
print(x.shape)
print(x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.Size([3, 3])
2


In [ ]:
x = x.view(9)
print(x)
print(x.size())
print(x.shape)
print(x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
torch.Size([9])
1


view로는 텐서의 원소 개수를 바꿀 수 없음|

In [ ]:
try:
  x = x.view(2,4)
except Exception as e:
  print(e)

shape '[2, 4]' is invalid for input of size 9


========================================================  
행렬곱 연산

In [4]:
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0,2.0], [3.0, 4.0], [5.0, 6.0]])
print(w.size())
print(x.size())
print(w)
print(x)

torch.Size([5, 3])
torch.Size([3, 2])
tensor([[-1.3821, -0.5399, -0.7708],
        [ 0.1470, -2.0191,  0.1004],
        [ 0.0344, -0.0568, -0.3968],
        [ 1.4434, -0.0089, -0.2476],
        [ 0.4937, -0.0307,  0.3876]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
b = torch.randn(5,2, dtype=torch.float)
print(b.size())
print(b)

torch.Size([5, 2])
tensor([[-0.4790,  1.0040],
        [-0.2322, -1.5613],
        [ 0.6274, -0.1727],
        [-0.1813,  0.1894],
        [-1.9842,  0.5550]])


In [ ]:
wx = torch.mm(w, x)
print(wx.size())
print(wx)

torch.Size([5, 2])
tensor([[10.2922, 11.6191],
        [-2.7537, -2.9527],
        [ 2.9347,  3.9853],
        [-0.7747, -2.5432],
        [ 0.6272,  0.9321]])


In [ ]:
result = wx + b
print(result.size())
print(result)

torch.Size([5, 2])
tensor([[ 9.8132, 12.6231],
        [-2.9859, -4.5139],
        [ 3.5620,  3.8126],
        [-0.9559, -2.3538],
        [-1.3570,  1.4871]])


========================================================  
autograd

In [5]:
w = torch.tensor(1.0, requires_grad=True)

In [6]:
a = w * 3

In [7]:
l = a ** 2

In [8]:
l.backward()
print('l을 w로 미분한 값은 {}'.format(w.grad))

l을 w로 미분한 값은 18.0


3.2 경사하강법으로 이미지 복원하기 