In [2]:
import numpy as np
import pprint

pp = pprint.PrettyPrinter(width=41, compact=True)

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10],[11,12]])
pp.pprint(a)
print(a.shape)
pp.pprint(b)
print(b.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])
(3, 2)
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])
(3, 2)


1)  np.concatenate

In [4]:
no_1 = np.concatenate((a, b), axis=0)
#행렬을 붙이는 계산
pp.pprint(no_1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])


In [5]:
print(a+b)
#그냥 더하면 broadcasting 연산으로 덧셈연산을 하게된다.

[[ 8 10]
 [12 14]
 [16 18]]


In [6]:
list_1 = [1,2,3]
list_2 = [4,5,6]
temp =list_1 + list_2 
print(temp)
#리스트는 바로 concatinate 연산을 하니 절대 헷갈리지 말 것
#배열과 리스트의 차이를 생각하면 편하다.

[1, 2, 3, 4, 5, 6]


In [7]:
#만약 다른 모양끼리 concat을 하면 어떨까?
c = np.array([[1,2],[3,4],[5,6]])
d = np.array([[1,2,3,4],[5,6,7]])
e = np.array([1,2,3,4])

<ipython-input-7-1520e8c4410c>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d = np.array([[1,2,3,4],[5,6,7]])


In [8]:
concat2 = np.concatenate((c,d), axis=0)
#같은 차원으로만 더해야 한다고 한다.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# 2)  np.stack, vstack, hstack

stack과 concat의 차이점?  
stack : Join a sequence of arrays along a new axis.  
concat: Join a sequence of arrays along an existing axis.  

여기서 차이점인, existing axis와 new_axis 차이는 뭘까?

In [9]:
arrays = [np.random.randn(2,3) for _ in range(4)]
print(arrays[0].shape)
print(arrays)

(2, 3)
[array([[ 1.98591611, -0.07317036, -1.03587676],
       [-1.16489752,  1.88911641, -0.55030062]]), array([[-2.25094399, -0.88938835, -1.46217387],
       [-1.02623026, -1.15285903, -0.60202051]]), array([[ 0.42168814,  1.7920859 , -2.07573402],
       [ 1.21356275,  1.59944232, -0.73524865]]), array([[-0.32177738,  0.53867131,  1.4056303 ],
       [ 0.60661546,  0.12733249,  1.15495727]])]


In [10]:
new_arr = np.stack(arrays, axis=0)
print(new_arr.shape)
print(new_arr)

(4, 2, 3)
[[[ 1.98591611 -0.07317036 -1.03587676]
  [-1.16489752  1.88911641 -0.55030062]]

 [[-2.25094399 -0.88938835 -1.46217387]
  [-1.02623026 -1.15285903 -0.60202051]]

 [[ 0.42168814  1.7920859  -2.07573402]
  [ 1.21356275  1.59944232 -0.73524865]]

 [[-0.32177738  0.53867131  1.4056303 ]
  [ 0.60661546  0.12733249  1.15495727]]]


In [11]:
new_arr_m1 = np.stack(arrays, axis=-1)
print(new_arr_m1.shape)
print(new_arr_m1)

(2, 3, 4)
[[[ 1.98591611 -2.25094399  0.42168814 -0.32177738]
  [-0.07317036 -0.88938835  1.7920859   0.53867131]
  [-1.03587676 -1.46217387 -2.07573402  1.4056303 ]]

 [[-1.16489752 -1.02623026  1.21356275  0.60661546]
  [ 1.88911641 -1.15285903  1.59944232  0.12733249]
  [-0.55030062 -0.60202051 -0.73524865  1.15495727]]]


In [12]:
new_arr1 = np.stack(arrays, axis=1)
print(new_arr1.shape)
print(new_arr1)

(2, 4, 3)
[[[ 1.98591611 -0.07317036 -1.03587676]
  [-2.25094399 -0.88938835 -1.46217387]
  [ 0.42168814  1.7920859  -2.07573402]
  [-0.32177738  0.53867131  1.4056303 ]]

 [[-1.16489752  1.88911641 -0.55030062]
  [-1.02623026 -1.15285903 -0.60202051]
  [ 1.21356275  1.59944232 -0.73524865]
  [ 0.60661546  0.12733249  1.15495727]]]


In [13]:
new_arr2 = np.stack(arrays, axis=2)
#new_arr3 = np.stack(arrays, axis=3) #axis가 3개니까 0,1,2 말곤 없겠지?
print(new_arr2.shape)
print(new_arr2)

(2, 3, 4)
[[[ 1.98591611 -2.25094399  0.42168814 -0.32177738]
  [-0.07317036 -0.88938835  1.7920859   0.53867131]
  [-1.03587676 -1.46217387 -2.07573402  1.4056303 ]]

 [[-1.16489752 -1.02623026  1.21356275  0.60661546]
  [ 1.88911641 -1.15285903  1.59944232  0.12733249]
  [-0.55030062 -0.60202051 -0.73524865  1.15495727]]]


독립된 3행 4열 np.array들을 단일 numpy array로 합쳤다.

3) np.append

numpy.append(arr, values, axis=None)  
Append values to the end of an array.  

In [14]:
np.append([1,2,3],[4,5,6],[7,8,9])

TypeError: 'list' object cannot be interpreted as an integer

4) np.newaxis, None ( newaxis 와 차이 비교 )

np.array의 차원을 늘려줌  
1D to 2D 2D to 3D... 

In [15]:
a1 = np.arange(4)
a1.shape

(4,)

#### 1
1D array를 row vec나 col vec로 사용하고 싶을경우   

Q. (4, ) 형태로 하면 껄끄럽다는데 무슨 이유일까?

In [16]:
# make it as row vector by inserting an axis along first dimension
row_vec = a1[np.newaxis, :]
row_vec.shape

(1, 4)

In [17]:
col_vec = a1[:, np.newaxis]
col_vec.shape

(4, 1)

#### 2.  
shape이 다른 array간 연산을 할 때도 유용.  

In [19]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
x1 + x2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

이런거를 이렇게

In [21]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

x1_new = x1[:, np.newaxis]
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

broad casting 연산이 가능하다!

5) np.reshape

In [17]:
print(a.shape)
a.reshape(3,2,1)
print(a.shape)

(3, 2)
(3, 2)


6) np.expand_dims