In [8]:
import numpy as np
import pprint

pp = pprint.PrettyPrinter(width=41, compact=True)

In [11]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10],[11,12]])
pp.pprint(a)
print(a.shape)
pp.pprint(b)
print(b.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])
(3, 2)
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])
(3, 2)


1)  np.concatenate

In [13]:
no_1 = np.concatenate((a, b), axis=0)
#행렬을 붙이는 계산
pp.pprint(no_1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])


In [6]:
print(a+b)
#그냥 더하면 broadcasting 연산으로 덧셈연산을 하게된다.

[[ 8 10]
 [12 14]
 [16 18]]


In [19]:
list_1 = [1,2,3]
list_2 = [4,5,6]
temp =list_1 + list_2 
print(temp)
#리스트는 바로 concatinate 연산을 하니 절대 헷갈리지 말 것
#배열과 리스트의 차이를 생각하면 편하다.

[1, 2, 3, 4, 5, 6]


In [22]:
#만약 다른 모양끼리 concat을 하면 어떨까?
c = np.array([[1,2],[3,4],[5,6]])
d = np.array([[1,2,3,4],[5,6,7]])
e = np.array([1,2,3,4])

<ipython-input-22-1520e8c4410c>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d = np.array([[1,2,3,4],[5,6,7]])


In [24]:
concat2 = np.concatenate((c,d), axis=0)
#같은 차원으로만 더해야 한다고 한다.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# 2)  np.stack, vstack, hstack

stack과 concat의 차이점?  
stack : Join a sequence of arrays along a new axis.  
concat: Join a sequence of arrays along an existing axis.  

여기서 차이점인, existing axis와 new_axis 차이는 뭘까?

In [55]:
arrays = [np.random.randn(2,3) for _ in range(4)]
print(arrays[0].shape)
print(arrays)

(2, 3)
[array([[ 1.61681734,  2.14880995,  0.06800799],
       [ 0.50987027, -1.16040776,  2.00851077]]), array([[-1.08192355,  1.25180471, -1.74640422],
       [ 1.88690038, -0.20903632, -0.62252835]]), array([[ 0.2582378 , -0.33014424, -0.63408707],
       [-1.18816754,  0.04725139, -0.97246026]]), array([[-0.66722394,  0.04198197, -0.65487798],
       [ 0.14602292, -0.13570086, -0.19563877]])]


In [56]:
new_arr = np.stack(arrays, axis=0)
print(new_arr.shape)
print(new_arr)

(4, 2, 3)
[[[ 1.61681734  2.14880995  0.06800799]
  [ 0.50987027 -1.16040776  2.00851077]]

 [[-1.08192355  1.25180471 -1.74640422]
  [ 1.88690038 -0.20903632 -0.62252835]]

 [[ 0.2582378  -0.33014424 -0.63408707]
  [-1.18816754  0.04725139 -0.97246026]]

 [[-0.66722394  0.04198197 -0.65487798]
  [ 0.14602292 -0.13570086 -0.19563877]]]


In [57]:
new_arr_m1 = np.stack(arrays, axis=-1)
print(new_arr_m1.shape)
print(new_arr_m1)

(2, 3, 4)
[[[ 1.61681734 -1.08192355  0.2582378  -0.66722394]
  [ 2.14880995  1.25180471 -0.33014424  0.04198197]
  [ 0.06800799 -1.74640422 -0.63408707 -0.65487798]]

 [[ 0.50987027  1.88690038 -1.18816754  0.14602292]
  [-1.16040776 -0.20903632  0.04725139 -0.13570086]
  [ 2.00851077 -0.62252835 -0.97246026 -0.19563877]]]


In [58]:
new_arr1 = np.stack(arrays, axis=1)
print(new_arr1.shape)
print(new_arr1)

(2, 4, 3)
[[[ 1.61681734  2.14880995  0.06800799]
  [-1.08192355  1.25180471 -1.74640422]
  [ 0.2582378  -0.33014424 -0.63408707]
  [-0.66722394  0.04198197 -0.65487798]]

 [[ 0.50987027 -1.16040776  2.00851077]
  [ 1.88690038 -0.20903632 -0.62252835]
  [-1.18816754  0.04725139 -0.97246026]
  [ 0.14602292 -0.13570086 -0.19563877]]]


In [59]:
new_arr2 = np.stack(arrays, axis=2)
#new_arr3 = np.stack(arrays, axis=3) #axis가 3개니까 0,1,2 말곤 없겠지?
print(new_arr2.shape)
print(new_arr2)

(2, 3, 4)
[[[ 1.61681734 -1.08192355  0.2582378  -0.66722394]
  [ 2.14880995  1.25180471 -0.33014424  0.04198197]
  [ 0.06800799 -1.74640422 -0.63408707 -0.65487798]]

 [[ 0.50987027  1.88690038 -1.18816754  0.14602292]
  [-1.16040776 -0.20903632  0.04725139 -0.13570086]
  [ 2.00851077 -0.62252835 -0.97246026 -0.19563877]]]


독립된 3행 4열 np.array들을 단일 numpy array로 합쳤다.

3) np.append

numpy.append(arr, values, axis=None)  
Append values to the end of an array.  

In [ ]:
np.append([1,2,3],[4,5,6],[7,8,9])

4) np.newaxis, None ( newaxis 와 차이 비교 )

5) np.reshape

In [17]:
print(a.shape)
a.reshape(3,2,1)
print(a.shape)

(3, 2)
(3, 2)


6) np.expand_dims