98pg numpy 부터|

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,'a'])

하나의 배열에는 동일한 데이터형만 들어갈 수 있다

In [4]:
a #즉 모두 글자로 들어간 것을 확인할 수 있다.

array(['1', '2', 'a'], dtype='<U11')

In [5]:
sample_array_2 = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
sample_array_2.shape

(2, 5)

In [7]:
np.arange(start = 1 , stop = 6, step=1)

array([1, 2, 3, 4, 5])

In [8]:
np.arange(start = 0.1, stop=0.8, step=0.2)

array([0.1, 0.3, 0.5, 0.7])

In [10]:
np.tile("A", 5) # 같은 값을 여러개 채우기

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [11]:
np.tile(0, 4)

array([0, 0, 0, 0])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [16]:
d1_array[0]

1

In [17]:
d1_array[1:3]

array([2, 3])

In [18]:
d2 = np.array(
[[1,2,3,4,5],
[6,7,8,9,10]])
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
d2[0][3:5]

array([4, 5])

In [21]:
d2[:][1]

array([ 6,  7,  8,  9, 10])

In [22]:
d2[1, 2:4]

array([8, 9])

In [28]:
d3 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [29]:
d3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
d3[:,2:3]

array([[ 3],
       [ 7],
       [11]])

In [32]:
sample_array = np.array([1,2,3,4,5])

DataFrame

In [33]:
sample_df = pd.DataFrame({
    'col1': sample_array,
    'col2': sample_array * 2,
    'col3':["A", "B","C","D","E"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [34]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [35]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(["A","B","C"])
})

df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(["D","E","F"])
})

In [36]:
pd.concat([df_1, df_2]) # same as axis = 0 

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [37]:
pd.concat([df_1, df_2], axis = 1)

col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

In [45]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [40]:
sample_df.col2

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32

In [41]:
sample_df["col2"]

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32

In [42]:
sample_df[["col2", "col3"]]

col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E

In [43]:
sample_df.drop("col1", axis=1)

col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E

In [44]:
sample_df.head(3)

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C

In [46]:
sample_df.query('index == 0')

col1  col2 col3
0     1     2    A

In [47]:
sample_df.query('col3 =="A"')

col1  col2 col3
0     1     2    A

In [48]:
sample_df.query('col3=="A" | col3 == "D"')

col1  col2 col3
0     1     2    A
3     4     8    D

In [49]:
sample_df.query('col3 == "A" & col1 == 3')

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [50]:
sample_df.query('col3 == "A"')[["col2","col3"]]

col2 col3
0     2    A

## Series

판다스 데이터 프레임에서 1열만 추출하면 시리즈라는 열 데이터형으로 바뀐다.

In [51]:
type(sample_df)

pandas.core.frame.DataFrame

In [52]:
type(np.array(sample_df.col1))

numpy.ndarray

시리즈는 배열과 비슷한 작업이 가능하지만, 배열 쪽이 좀 더 사용하기 쉽다.
시리즈를 배열로 변환하려면 np.array의 인수로 시리즈형 변수를 넘기면 된다

In [53]:
type(sample_df.col1.values)

numpy.ndarray

In [54]:
help(sample_df.query)

Help on method query in module pandas.core.frame:

query(expr, inplace=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that contain spaces or operators by
        surrounding them in backticks. This way you can also escape
        names that start with a digit, or those that  are a Python keyword.
        Basically when it is not valid Python identifier. See notes down
        for more details.
    
        For example, if one of your columns is called ``a a`` and you want
        to sum it with ``b``, your query should be ```a a` + b``.
    
        .. versionadded:: 0.25.0
            Backtick quoting introduced.
    
        .. versionadded:: 1.0

그래서...시리즈는??

# 111pg. CH3. 파이썬을 이용한 데이터 분석

In [55]:
import scipy as sp

In [57]:
%precision 3 #소수점 자리 제한

'%.3f'

In [60]:
#물고기의 몸 길이라는 1가지 종류의 데이터뿐일 경우 "1변량 데이터"라고 부름
fish = np.array([2,3,3,4,4,4,4,5,5,6])

In [61]:
sp.sum(fish)

<ipython-input-61-e38e77ae5f93>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum(fish)


40

In [63]:
len(fish)

10

In [64]:
N = len(fish)
sum_value = sp.sum(fish)
mu = sum_value / N
mu

<ipython-input-64-2b8f1e9fae35>:2: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sum_value = sp.sum(fish)


4.0

In [65]:
sp.mean(fish)

<ipython-input-65-f5101e6bec6a>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish)


4.0

In [66]:
sigma_2_sample = sp.sum((fish - mu)**2) / N
sigma_2_sample

<ipython-input-66-c2a1e076a7c6>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2_sample = sp.sum((fish - mu)**2) / N


1.2

In [73]:
sp.var(fish, ddof = 0) # ddof ?? 뭐지 

<ipython-input-73-c200c91aab63>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish, ddof = 0) # ddof ?? 뭐지


1.2

표본분산은, 표본의 평균을 사용해 분산을 계산한 값.  
이 값은 분산을 과소추정하는 경향이 있음  
  
그 경향을 없애기 위한 것이 #불편분산

In [75]:
sigma_2 = sp.sum((fish - mu) **2) / (N - 1)
sigma_2

<ipython-input-75-04117ac7426f>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sigma_2 = sp.sum((fish - mu) **2) / (N - 1)


1.3333333333333333

In [76]:
sp.var(fish, ddof=1)

<ipython-input-76-fa1a9d4f0b5e>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish, ddof=1)


1.3333333333333333

표준편차 : 분산은 데이터를 제곱해서 계산했다. 그래서 단위 등도 제곱이 되는데
이 상태로는 계산이 불편하다. 그래서 분산에 루트를 취한 표준편차를 이용한다.

In [78]:
sigma = sp.sqrt(sigma_2)
sigma

<ipython-input-78-ad5d08f7a564>:1: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  sigma = sp.sqrt(sigma_2)


1.1547005383792515

In [79]:
sp.std(fish, ddof=1)

<ipython-input-79-793bafbe34b3>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish, ddof=1)


1.1547005383792515

# 3.1.8 표준화

데이터의 평균을 0으로, 표준편차(분산)를 1로 하는 변환을 "표준화"라 한다  

데이터끼리 비교하기 쉽게   

In [80]:
fish - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [81]:
sp.mean(fish - mu)

<ipython-input-81-8cc55d6a1497>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish - mu)


0.0

In [82]:
fish / sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [84]:
sp.std(fish / sigma, ddof = 1)

<ipython-input-84-50ceaa5f110a>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish / sigma, ddof = 1)


1.0

In [85]:
standard = (fish - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [90]:
np.mean(standard) #0이나 다를 바 없이 작은 수

2.2204460492503132e-17

In [91]:
np.std(standard, ddof = 1)

1.0

In [ ]:
np.amax(fish)

In [95]:
np.amin(fish)

2

In [96]:
np.median(fish)

4.0

In [97]:
fish_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [98]:
np.mean(fish_2)

13.4

In [99]:
np.median(fish_2)

4.0

사분위 수 

In [100]:
from scipy import stats

In [104]:
fish_3 = np.array([1,2,3,4,5,6,7,8,9,10])
stats.scoreatpercentile(fish_3, 25) # 아래서부터 25% 값 

3.25

In [105]:
stats.scoreatpercentile(fish_3, 75)

7.75

In [106]:
stats.scoreatpercentile(fish_3, 85)

8.649999999999999

120pg까지