98pg numpy 부터|

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,'a'])

하나의 배열에는 동일한 데이터형만 들어갈 수 있다

In [4]:
a #즉 모두 글자로 들어간 것을 확인할 수 있다.

array(['1', '2', 'a'], dtype='<U11')

In [5]:
sample_array_2 = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
sample_array_2.shape

(2, 5)

In [7]:
np.arange(start = 1 , stop = 6, step=1)

array([1, 2, 3, 4, 5])

In [8]:
np.arange(start = 0.1, stop=0.8, step=0.2)

array([0.1, 0.3, 0.5, 0.7])

In [10]:
np.tile("A", 5) # 같은 값을 여러개 채우기

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [11]:
np.tile(0, 4)

array([0, 0, 0, 0])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [16]:
d1_array[0]

1

In [17]:
d1_array[1:3]

array([2, 3])

In [18]:
d2 = np.array(
[[1,2,3,4,5],
[6,7,8,9,10]])
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
d2[0][3:5]

array([4, 5])

In [21]:
d2[:][1]

array([ 6,  7,  8,  9, 10])

In [22]:
d2[1, 2:4]

array([8, 9])

In [28]:
d3 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [29]:
d3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
d3[:,2:3]

array([[ 3],
       [ 7],
       [11]])

In [32]:
sample_array = np.array([1,2,3,4,5])

DataFrame

In [33]:
sample_df = pd.DataFrame({
    'col1': sample_array,
    'col2': sample_array * 2,
    'col3':["A", "B","C","D","E"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [34]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [35]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(["A","B","C"])
})

df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(["D","E","F"])
})

In [36]:
pd.concat([df_1, df_2]) # same as axis = 0 

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [37]:
pd.concat([df_1, df_2], axis = 1)

col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

In [45]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [40]:
sample_df.col2

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32

In [41]:
sample_df["col2"]

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int32

In [42]:
sample_df[["col2", "col3"]]

col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E

In [43]:
sample_df.drop("col1", axis=1)

col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E

In [44]:
sample_df.head(3)

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C

In [46]:
sample_df.query('index == 0')

col1  col2 col3
0     1     2    A

In [47]:
sample_df.query('col3 =="A"')

col1  col2 col3
0     1     2    A

In [48]:
sample_df.query('col3=="A" | col3 == "D"')

col1  col2 col3
0     1     2    A
3     4     8    D

In [49]:
sample_df.query('col3 == "A" & col1 == 3')

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [50]:
sample_df.query('col3 == "A"')[["col2","col3"]]

col2 col3
0     2    A

## Series

In [51]:
type(sample_df)

pandas.core.frame.DataFrame